"use client";
import { useState } from "react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
const photos=[
"01-WhatsApp-Image-2026-09-22-at-10.45.18-AM-1-.jpeg","02-WhatsApp-Image-2026-09-22-at-10.45.18-AM-2-.jpeg","03-WhatsApp-Image-2026-09-22-at-10.45.06-AM-1-.jpeg","04-WhatsApp-Image-2026-09-22-at-10.45.06-AM.jpeg","05-WhatsApp-Image-2026-09-22-at-10.45.03-AM.jpeg","06-WhatsApp-Image-2026-09-22-at-10.45.04-AM-1-.jpeg","07-WhatsApp-Image-2026-09-22-at-10.45.04-AM.jpeg","08-WhatsApp-Image-2026-09-22-at-10.45.05-AM-1-.jpeg","09-WhatsApp-Image-2026-09-22-at-10.45.05-AM-2-.jpeg","10-WhatsApp-Image-2026-09-22-at-10.45.05-AM.jpeg","11-WhatsApp-Image-2026-09-22-at-10.45.18-AM.jpeg","12-WhatsApp-Image-2026-09-22-at-10.45.02-AM-2-.jpeg"];
const products=[
{name:"Palillos redondos",use:"Para fruta y alimentos en palillo",pictures:[0,2]},
{name:"Palitos para paleta",use:"Formato plano con extremos redondeados",pictures:[3,5,10]},
{name:"Palillos con punta",use:"Para brochetas y preparación de alimentos",pictures:[6,8,9]},
{name:"Palitos de sección cuadrada",use:"Madera en formato recto",pictures:[4,7,11]},
{name:"Palitas de madera",use:"Formato corto con contorno curvo",pictures:[1]}
];
export default function Home(){
 const [view,setView]=useState("slides"),[active,setActive]=useState(0),[photo,setPhoto]=useState(0);
 const change=(n:number)=>{setActive((n+products.length)%products.length);setPhoto(0)};
 const product=products[active];
 return <main id="inicio">
 <header className="nav"><a className="brand" href="#inicio"><strong>MAZ<span>+</span></strong><small>PALILLOS<br/>DE MADERA</small></a><nav aria-label="Navegación"><a href="#empresa">Empresa</a><a href="#productos">Productos</a><a href="#contacto">Contacto</a></nav><a className="button small" href="#contacto">Solicitar cotización</a></header>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">MAZ+ / PALILLOS DE MADERA</p><h1>La madera.<br/>El producto.<br/><em>Tu siguiente idea.</em></h1><p className="lead">Palillos y palitos de madera para frutas, paletas de hielo y alimentos. Explora nuestros formatos y encuentra el indicado para tu negocio.</p><a className="button" href="#productos">Explorar productos <span>↗</span></a></div><div className="hero-photo"><img src={"/products/"+photos[10]} alt="Palitos de madera para paleta, fotografía de producto MAZ" fetchPriority="high"/><div className="photo-caption"><span>HECHOS PARA EL DÍA A DÍA</span><span>01 / MADERA</span></div></div></section>
 <section className="about" id="empresa"><p className="eyebrow">01 / EMPRESA</p><h2>Una pieza sencilla.<br/>Muchas posibilidades.</h2><div><p>En MAZ+ ofrecemos palillos de madera en distintos formatos para acompañar la preparación y presentación de tus productos.</p><p>Desde palitos planos para paletas hasta formatos con punta para alimentos, nuestro catálogo reúne opciones para diferentes aplicaciones.</p></div></section>
 <section className="catalog" id="productos"><div className="catalog-head"><div><p className="eyebrow">02 / NUESTROS PRODUCTOS</p><h2>Encuentra tu formato.</h2></div><Tabs value={view} onValueChange={setView}><TabsList className="view-tabs" aria-label="Vista del catálogo"><TabsTrigger value="slides">Slides</TabsTrigger><TabsTrigger value="grid">Grid</TabsTrigger></TabsList></Tabs></div>
 {view==="slides"?<div className="slider"><div className="product-visual"><img src={"/products/"+photos[product.pictures[photo]]} alt={product.name+" · vista "+(photo+1)}/><div className="thumbs">{product.pictures.map((p,i)=><button key={p} aria-label={"Ver fotografía "+(i+1)+" de "+product.name} aria-pressed={photo===i} onClick={()=>setPhoto(i)}><img src={"/products/"+photos[p]} alt=""/></button>)}</div></div><div className="slide-info"><p className="eyebrow">FORMATO {String(active+1).padStart(2,"0")} / 05</p><h3>{product.name}</h3><p>{product.use}</p><p className="muted">Consulta medidas, presentaciones y disponibilidad con nuestro equipo.</p><a className="text-link" href="#contacto">Consultar este formato ↗</a><div className="slide-controls"><button onClick={()=>change(active-1)} aria-label="Producto anterior">←</button><span aria-live="polite">{active+1} / {products.length}</span><button onClick={()=>change(active+1)} aria-label="Producto siguiente">→</button></div></div></div>:<div className="product-grid">{products.map((p,i)=><article key={p.name}><button className="grid-photo" onClick={()=>{change(i);setView("slides")}} aria-label={"Ver todas las fotografías de "+p.name}><img loading="lazy" src={"/products/"+photos[p.pictures[0]]} alt={p.name}/></button><p className="eyebrow">FORMATO 0{i+1}</p><h3>{p.name}</h3><p>{p.use}</p><button className="text-link" onClick={()=>{change(i);setView("slides")}}>Ver fotografías ({p.pictures.length}) ↗</button></article>)}</div>}
 </section>
 <section className="technical" id="catalogo"><div><p className="eyebrow">FICHA TÉCNICA</p><h2>Palo elotero<br/>con punta.</h2><p>Consulta la especificación del producto y su presentación a granel.</p><a className="button" href="/palo-elotero.pdf" download>Descargar ficha PDF ↓</a></div><dl><div><dt>Largo</dt><dd>20 cm</dd></div><div><dt>Ancho</dt><dd>8.2 mm</dd></div><div><dt>Especie</dt><dd>Pino</dd></div><div><dt>Presentación</dt><dd>Bulto a granel · 25 kg</dd></div></dl></section>
 <section className="contact" id="contacto"><div><p className="eyebrow">03 / CONTACTO</p><h2>Hablemos de<br/>tu próximo pedido.</h2><p>Para preparar tu cotización, indica el formato, las medidas y la cantidad que necesitas.</p></div><div className="contact-details"><div><span>WhatsApp / Teléfono</span><p>Por confirmar</p></div><div><span>Correo de ventas</span><p>Por confirmar</p></div><div><span>Ubicación</span><p>Por confirmar</p></div><small>Los canales de atención se habilitarán al confirmar los datos de la empresa.</small></div></section>
 <footer><a className="brand" href="#inicio"><strong>MAZ<span>+</span></strong><small>PALILLOS<br/>DE MADERA</small></a><p>© 2026 MAZ+ · Palillos de madera</p><a href="#inicio">Volver al inicio ↑</a></footer>
 </main>
}
